
const MIN_DAILY_VOLUME_USD = 500000;
const MIN_DAILY_LIQUIDITY_USD = 100000;
const LIQUIDITY_V3 = true;

const MULTIPLIER = 15;

const TIME_INTERVALS_IN_DAYS = [1, 4/24, 2/24, 1/24 ];
const DATES = TIME_INTERVALS_IN_DAYS.map(x=> Math.round(Date.now() / 1000 - (86400 * x)));
const NUMBEROFDAYS = 1;
const TIME_IN_RANGE_TRESHOLD = 0.7;
const NUMBEROFDAYS_HISTORICAL = 2;
const DATE = Math.round(Date.now() / 1000 - (86400 * NUMBEROFDAYS));
const DATE_HISTORICAL = Math.round(Date.now() / 1000 - (86400 * NUMBEROFDAYS_HISTORICAL));
const FRAME_SIZE_FOR_SWAP_SCAN  = 1440 * 6; // one hour * 6


module.exports = {
    MIN_DAILY_VOLUME_USD,
    MIN_DAILY_LIQUIDITY_USD,
    MULTIPLIER,
    TIME_INTERVALS_IN_DAYS,
    DATES,
    NUMBEROFDAYS,
    TIME_IN_RANGE_TRESHOLD,
    NUMBEROFDAYS_HISTORICAL,
    DATE,
    DATE_HISTORICAL,
    FRAME_SIZE_FOR_SWAP_SCAN,
};
